name = "irakli"
surname = "gegia"
first = "is"
age = "11"
second = "years"
third = "old."
pronoun = "he"
fourth = "lives"
fifth = "in"
country = "georgia,"
sixth = "in"
seventh = "martvili."
print (name + " " + surname + " " + first + " " + second + " " + third + " " + pronoun + " " + fourth + " " + fifth + " " + country + " " + sixth + " " + seventh)
